id: I9838A898
legacy_id: P010691
ocr_import_info:
  bdrc_scan_id: W27556
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T07:53:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:30:19.302001+00:00'
last_modified: 2022-09-02 15:30:30.167604
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27556
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27556
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲིས་ལན་བླང་དོར་རབ་གསལ་སྣང་བའི་གཞུང་རྣམ་པར་དག་པའི་ཡི་གེ་ལུང་དང་མཐུན་པ།
  author: ས་བཟང་མ་ཏི་པཎ་ཆེན་བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.6036482634708137
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I4384:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4384
      total_pages: 102
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I4384.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6036482634708137
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
