id: I9838A898
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:54:34+00:00'
last_modified: '2022-06-08T16:50:14.532226+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27556
  title: དྲིས་ལན་བླང་དོར་རབ་གསལ་སྣང་བའི་གཞུང་རྣམ་པར་དག་པའི་ཡི་གེ་ལུང་དང་མཐུན་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    428D:
      image_group_id: I4384
      title: ''
      total_pages: 102
      order: 1
      base_file: 428D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
