id: P010691
initial_creation_type: ocr
source_metadata:
  id: bdr:W27556
  title: དྲིས་ལན་བླང་དོར་རབ་གསལ་སྣང་བའི་གཞུང་རྣམ་པར་དག་པའི་ཡི་གེ་ལུང་དང་མཐུན་པ
  author: ''
  volumes:
    84fa7be4e246495588443845c44a37d2:
      image_group_id: I4384
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
