id: P010691
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:07.714892
source_metadata:
  id: bdr:W27556
  title: དྲིས་ལན་བླང་དོར་རབ་གསལ་སྣང་བའི་གཞུང་རྣམ་པར་དག་པའི་ཡི་གེ་ལུང་དང་མཐུན་པ
  author: ''
  volumes:
    84fa7be4e246495588443845c44a37d2:
      image_group_id: I4384
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
